apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: default
  labels:
    app: sonarqube
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: sonarqube