{{- $as := .Values.autoscaling | default dict -}}
{{- if ($as.enabled | default false) -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pg.fullname" . }}
  labels:
    {{- include "pg.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pg.fullname" . }}
  minReplicas: {{ $as.minReplicas | default 1 }}
  maxReplicas: {{ $as.maxReplicas | default 1 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $as.targetCPUUtilizationPercentage | default 80 }}
{{- end }}
