replicaCount: 1

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: "8.13.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9200
  name: http

resources:
  requests:
    cpu: "250m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

persistence:
  enabled: false
  size: 10Gi
  storageClass: ""

env:
  - name: discovery.type
    value: single-node
  - name: xpack.security.enabled
    value: "false"
  - name: ES_JAVA_OPTS
    value: "-Xms512m -Xmx512m"

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: elasticsearch.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
