apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch-simple.fullname" . }}
  labels:
    {{- include "elasticsearch-simple.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "elasticsearch-simple.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: 9200
      protocol: TCP
