apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-data
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: ""  # Leave empty or set to "local-path" if needed
