apiVersion: v1
kind: Secret
metadata:
  name: oracle-credentials
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  ORACLE_PASSWORD: "StrongPassw0rd!"
