apiVersion: v1
kind: Service
metadata:
  name: oracle
  namespace: default
spec:
  type: NodePort
  selector:
    app: oracle
  ports:
    - port: 1521
      targetPort: 1521
      nodePort: 31521  # You can change this port if needed (range: 30000-32767)
