# -- Image to run
image:
  repository: ghcr.io/gvenzl/oracle-xe
  tag: "21.3.0"
  pullPolicy: IfNotPresent
  # If you use official Oracle registry, set this and create a secret (see step 8)
  pullSecrets: []   # e.g. ["oracle-regcred"]

# -- Basic K8s
nameOverride: ""
fullnameOverride: ""

# -- Service
service:
  type: NodePort
  port: 1521
  nodePort: 31521

# -- Storage
persistence:
  enabled: true
  storageClass: ""      # e.g. "local-path" or your CSI class
  accessModes: ["ReadWriteOnce"]
  size: 20Gi
  existingClaim: ""     # set if you want to use a pre-created PVC

# -- Resources (tune for your cluster)
resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

# -- Environment (XE image)
# ORACLE_DATABASE is the PDB/service name (XE image uses this as SERVICE_NAME)
env:
  ORACLE_DATABASE: "XEPDB1"
  ORACLE_CHARACTERSET: "AL32UTF8"   # optional
  APP_USER: "admin"                      # optional app user
  APP_USER_PASSWORD: "abc"             # optional app user password

# -- Put strong password via Secret, not plaintext
existingSecretName: "my-oracle-credentials"
oraclePassword: ""  # ignored

# -- Optional: run SQL on first boot (ConfigMap with .sql files)
initSql:
  enabled: false
  files: {}  # key: filename.sql, value: |
             #   CREATE USER demo IDENTIFIED BY "demo";
             #   GRANT CONNECT, RESOURCE TO demo;

# --- Probes: give Oracle enough time on first boot
podSecurityContext:
  enabled: true
  fsGroup: 54321
  fsGroupChangePolicy: OnRootMismatch

probes:
  # legacy keys you already had:
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 20
  initialDelaySeconds: 60  # (not used now; replaced by the two below)
  # new keys (safer defaults for Oracle first boot):
  readinessInitialDelay: 900
  livenessInitialDelay: 1200
  startup:
    enabled: true
    tcpPort: 1521
    periodSeconds: 10
    failureThreshold: 120
    timeoutSeconds: 5

serviceAccount:
  create: false
  name: ""
  annotations: {}
  imagePullSecrets: []   # e.g. [{name: oracle-regcred}]
  secrets: []
  automountServiceAccountToken: false

tests:
  enabled: true   # or false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  # behavior: {}   # optional HPA behavior