apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: sonarqube
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path   # <== CHANGE if needed

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sonarqube
  labels: { app: postgres }
spec:
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - name: psql
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: sonarqube-db, key: username } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: sonarqube-db, key: password } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: sonarqube-db, key: database } }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sonarqube
spec:
  selector: { app: postgres }
  ports:
    - name: psql
      port: 5432
      targetPort: 5432
