apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db
  namespace: sonarqube
type: Opaque
stringData:
  username: sonar
  password: "Ut12345678!"
  jdbcUrl: "jdbc:postgresql://postgresql-postgresql.default.svc.cluster.local:5432/sonarqube?sslmode=disable&currentSchema=public"
