apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - name: http
      port: 9000        # service port (inside cluster)
      targetPort: 9000  # container port
      nodePort: 30890   # external port on each node (must be 30000-32767)
