# Default values for sonarqube
replicaCount: 1

image:
  repository: sonarqube
  tag: "10.6.0-community"  # Use the desired SonarQube version
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

postgresql:
  enabled: true
  host: "postgresql-postgresql.default.svc.cluster.local"
  port: 5432
  database: "sonarqube"
  username: "sonar"
  password: "Ut12345678!"

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

persistence:
  enabled: true
  storageClass: "local-path"  # Specify your storage class if needed
  size: 8Gi

ingress:
  enabled: false  # Enable and configure if you want Ingress
  annotations: {}
  hosts:
    - host: sonarqube.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Additional SonarQube configurations
sonarqube:
  env:
    - name: SONAR_JDBC_URL
      value: "jdbc:postgresql://{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
    - name: SONAR_JDBC_USERNAME
      value: "{{ .Values.postgresql.username }}"
    - name: SONAR_JDBC_PASSWORD
      value: "{{ .Values.postgresql.password }}"