replicaCount: 1

image:
  repository: wso2/wso2am
  tag: "4.4.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePorts:
    ui: 30443
    gatewayHttps: 30243
    gatewayHttp: 30280

resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "1"

deploymentToml: |
  [server]
  hostname = "192.168.8.22"
  node_ip = "192.168.8.22"

  [transport.https]
  port = 9443
  proxyPort = 30443

  [super_admin]
  username = "admin"
  password = "admin"
  create_admin_account = true

  [database.shared_db]
  type = "h2"
  url = "jdbc:h2:./repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
  username = "wso2carbon"
  password = "wso2carbon"

  [apim.publisher]
  url = "https://192.168.8.22:30443/publisher"

  [apim.devportal]
  url = "https://192.168.8.22:30443/devportal"



