image:
  repository: grafana/grafana
  tag: "11.1.0"
  pullPolicy: IfNotPresent

replicaCount: 1

serviceAccount:
  create: true
  name: ""

service:
  type: NodePort
  port: 3000
  nodePort: 32542
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: grafana.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: 8Gi
  storageClass: ""

adminUser: "admin"
adminPassword: "admin123"  # change me (or set existingSecret)

existingSecret: ""   # if set, must contain keys: GF_SECURITY_ADMIN_USER, GF_SECURITY_ADMIN_PASSWORD

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://192.168.8.22:32442
        isDefault: true
        basicAuth: false

      - name: Tempo
        type: tempo
        access: proxy
        url: http://192.168.8.22:32532
        jsonData:
          httpMethod: GET
          tracesToLogsV2:
            datasourceUid: 'loki'
          serviceMap:
            datasourceUid: 'prometheus'
          search:
            hide: false
          nodeGraph:
            enabled: true

dashboards:
  example:
    enabled: true
