loki:
  image:
    repository: grafana/loki
    tag: 2.9.0
    pullPolicy: IfNotPresent
  enabled: true

  config:
    ingester:
      wal:
        dir: /var/loki/wal
    schema_config:
      configs:
        - from: 2020-10-15
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/boltdb-cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClassName: standard
    existingClaim: loki-storage

  extraVolumeMounts:
    - name: loki-storage
      mountPath: /var/loki

  extraVolumes:
    - name: loki-storage
      persistentVolumeClaim:
        claimName: loki-storage

service:
  type: NodePort
  port: 3100
  nodePort: 31300


persistence:
  enabled: true
  existingClaim: ""          # if set, chart won't create a PVC
  claimName: loki-data-pvc  # used when existingClaim == ""
  size: 50Gi
  accessModes: [ReadWriteOnce]
  storageClass: local-path
  mountPath: /var/loki
  fixPermissions: true       # runs an initContainer chown