replicaCount: 1

image:
  repository: grafana/loki
  tag: "2.9.8"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}

podSecurityContext:
  runAsUser: 10001
  runAsNonRoot: true
  fsGroup: 10001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 3100
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: loki.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""  # set to your StorageClass name or leave empty
  accessModes:
    - ReadWriteOnce

# Extra environment variables for the container
extraEnv: []

# Node scheduling
nodeSelector: {}
tolerations: []
affinity: {}

# Loki configuration (single process + boltdb-shipper + filesystem object store)
lokiConfig:
  ingester:
      wal:
        enabled: true
        dir: /data/loki/wal
  server:
    http_listen_port: 3100
    http_listen_address: 0.0.0.0
    log_level: info
  limits_config:
    ingestion_rate_mb: 8
    ingestion_burst_size_mb: 16
    max_streams_per_user: 100000
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    retention_period: 168h
  schema_config:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/index
      cache_location: /data/loki/boltdb-cache
      shared_store: filesystem
    filesystem:
      directory: /data/loki/chunks
  compactor:
    working_directory: /data/loki/compactor
    shared_store: filesystem
    compaction_interval: 5m
    retention_enabled: true
  ruler:
    storage:
      type: local
      local:
        directory: /data/loki/rules
    rule_path: /tmp/loki/rules-temp
    alertmanager_url: ""
    ring:
      kvstore:
        store: inmemory
    enable_api: true
