{{- $as := .Values.autoscaling | default dict -}}
{{- if ($as.enabled | default false) -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nexus.fullname" . }}
  minReplicas: {{ $as.minReplicas | default 1 }}
  maxReplicas: {{ $as.maxReplicas | default 3 }}
  {{- $cpu := $as.targetCPUUtilizationPercentage | default 80 -}}
  {{- $mem := $as.targetMemoryUtilizationPercentage | default nil -}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $cpu }}
    {{- if $mem }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $mem }}
    {{- end }}
{{- end }}
