apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prom.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.scrapeInterval }}
      evaluation_interval: {{ .Values.evaluationInterval }}
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
{{- with .Values.extraScrapeConfigs }}
{{- if . }}
      {{- toYaml . | nindent 6 }}
{{- end }}
{{- end }}
