apiVersion: v1
kind: Service
metadata:
  name: {{ include "wso2am.fullname" . }}
  labels:
    {{- include "wso2am.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ui
      port: 9443
      targetPort: 9443
      nodePort: {{ .Values.service.nodePorts.ui }}
    - name: gateway-https
      port: 8243
      targetPort: 8243
      nodePort: {{ .Values.service.nodePorts.gatewayHttps }}
    - name: gateway-http
      port: 8280
      targetPort: 8280
      nodePort: {{ .Values.service.nodePorts.gatewayHttp }}
  selector:
    {{- include "wso2am.selectorLabels" . | nindent 4 }}
