apiVersion: v1
kind: Service
metadata:
  name: {{ include "wso2am.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "wso2am.selectorLabels" . | nindent 4 }}
  ports:
    - port: 9443
      targetPort: 9443
      nodePort: {{ .Values.service.nodePorts.ui }}
      protocol: TCP
      name: ui
    - port: 8243
      targetPort: 8243
      nodePort: {{ .Values.service.nodePorts.gatewayHttps }}
      protocol: TCP
      name: gateway-https
    - port: 8280
      targetPort: 8280
      nodePort: {{ .Values.service.nodePorts.gatewayHttp }}
      protocol: TCP
      name: gateway-http
