replicas: 1

image:
  repository: sonatype/nexus3
  tag: latest
  pullPolicy: IfNotPresent

deploymentStrategy:
  type: Recreate            # prevents two pods mounting H2 at the same time

nexus:
  cleanupH2Locks: true
  terminationGraceSeconds: 120
  preStopSleepSeconds: 15
  # Optional JVM tuning (helps avoid OOM on first boot)
  # install4jAddVmParams: "-Xms1g -Xmx1.2g -XX:MaxDirectMemorySize=768m -XX:+UnlockExperimentalVMOptions -XX:ActiveProcessorCount=2"

probes:
  startup:
    enabled: true
    path: /
    periodSeconds: 10
    failureThreshold: 60

ports:
  ui: 8081
  docker:
    enabled: false
    port: 5000

service:
  type: NodePort
  uiPort: 8081
  uiNodePort: 30082
  dockerNodePort: 30083

persistence:
  enabled: true
  existingClaim: ""          # if set, chart won't create a PVC
  claimName: nexus-data-pvc  # used when existingClaim == ""
  size: 50Gi
  accessModes: [ReadWriteOnce]
  storageClass: local-path
  mountPath: /nexus-data
  fixPermissions: true       # runs an initContainer chown

resources:
  requests:
    cpu: "400m"
    memory: "4Gi"
  limits:
    cpu: "2"
    memory: "8Gi"

securityContext:
  runAsUser: 200
  runAsGroup: 200
  fsGroup: 200
  fsGroupChangePolicy: OnRootMismatch

readinessProbe:
  path: /
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

livenessProbe:
  path: /
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 10

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: false

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 75
