{{- if .Values.datasources.enabled | default true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.datasources.prometheus.url | default "http://localhost:9090" | quote }}
        isDefault: true
        basicAuth: {{ .Values.datasources.prometheus.basicAuth | default false }}
        {{- if .Values.datasources.prometheus.basicAuth }}
        basicAuthUser: {{ .Values.datasources.prometheus.basicAuthUser | quote }}
        secureJsonData:
          basicAuthPassword: {{ .Values.datasources.prometheus.basicAuthPassword | quote }}
        {{- end }}

      - name: Tempo
        type: tempo
        access: proxy
        url: {{ .Values.datasources.tempo.url | default "http://localhost:3100" | quote }}
        jsonData:
          httpMethod: GET
          tracesToLogsV2:
            datasourceUid: {{ .Values.datasources.tempo.tracesToLogsUid | default "loki" | quote }}
          serviceMap:
            datasourceUid: {{ .Values.datasources.tempo.serviceMapUid | default "prometheus" | quote }}
          search:
            hide: false
          nodeGraph:
            enabled: true
{{- end }}
