apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oracle-db.fullname" . }}
  labels:
    {{- include "oracle-db.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oracle-db.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate   # database container; avoid two pods using the same PVC
  template:
    metadata:
      labels:
        {{- include "oracle-db.labels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}

      {{- /* Optional pod security context for PVC permissions (e.g., local-path) */}}
      {{- if and .Values.podSecurityContext .Values.podSecurityContext.enabled }}
      securityContext:
        {{- with .Values.podSecurityContext.fsGroup }}
        fsGroup: {{ . }}
        {{- end }}
        {{- with .Values.podSecurityContext.fsGroupChangePolicy }}
        fsGroupChangePolicy: {{ . | quote }}
        {{- end }}
      {{- end }}

      containers:
        - name: oracle
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 1521
              name: tcp-1521

          env:
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.existingSecretName }}{{ .Values.existingSecretName }}{{ else }}{{ include "oracle-db.fullname" . }}-credentials{{ end }}
                  key: ORACLE_PASSWORD
            - name: ORACLE_DATABASE
              value: {{ .Values.env.ORACLE_DATABASE | quote }}
            {{- if .Values.env.ORACLE_CHARACTERSET }}
            - name: ORACLE_CHARACTERSET
              value: {{ .Values.env.ORACLE_CHARACTERSET | quote }}
            {{- end }}
            {{- if .Values.env.APP_USER }}
            - name: APP_USER
              value: {{ .Values.env.APP_USER | quote }}
            - name: APP_USER_PASSWORD
              value: {{ required "APP_USER_PASSWORD required when APP_USER is set" .Values.env.APP_USER_PASSWORD | quote }}
            {{- end }}

          volumeMounts:
            - name: oradata
              mountPath: /opt/oracle/oradata
            {{- if and .Values.initSql.enabled .Values.initSql.files }}
            - name: init-sql
              mountPath: /container-entrypoint-initdb.d
            {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- /* === Probes ===
                Backward-compat: falls back to your existing .Values.probes.*
                You can also set .Values.probes.startup.enabled/periodSeconds/failureThreshold/timeoutSeconds
          */}}

          # Give Oracle time to initialize on first boot (unpack/create DB)
          {{- $startupEnabled := (default true (dig "probes" "startup" "enabled" .Values)) -}}
          {{- $startupPort := (default 1521 (dig "probes" "startup" "tcpPort" .Values)) -}}
          {{- $startupPeriod := (default (default 10 (dig "probes" "periodSeconds" .Values)) (dig "probes" "startup" "periodSeconds" .Values)) -}}
          {{- $startupFail := (default 120 (dig "probes" "startup" "failureThreshold" .Values)) -}}
          {{- $startupTimeout := (default (default 5 (dig "probes" "timeoutSeconds" .Values)) (dig "probes" "startup" "timeoutSeconds" .Values)) -}}
          {{- if $startupEnabled }}
          startupProbe:
            tcpSocket:
              port: {{ $startupPort }}
            periodSeconds: {{ $startupPeriod }}
            failureThreshold: {{ $startupFail }}
            timeoutSeconds: {{ $startupTimeout }}
          {{- end }}

          # Readiness (begin late)
          {{- $readInit := (default 900 (dig "probes" "readinessInitialDelay" .Values)) -}}
          {{- $period := (default 15 (dig "probes" "periodSeconds" .Values)) -}}
          {{- $timeout := (default 5 (dig "probes" "timeoutSeconds" .Values)) -}}
          {{- $fail := (default 20 (dig "probes" "failureThreshold" .Values)) -}}
          readinessProbe:
            tcpSocket:
              port: {{ $startupPort }}
            initialDelaySeconds: {{ $readInit }}
            periodSeconds: {{ $period }}
            timeoutSeconds: {{ $timeout }}
            failureThreshold: {{ $fail }}

          # Liveness (begin even later)
          {{- $liveInit := (default 1200 (dig "probes" "livenessInitialDelay" .Values)) -}}
          livenessProbe:
            tcpSocket:
              port: {{ $startupPort }}
            initialDelaySeconds: {{ $liveInit }}
            periodSeconds: {{ $period }}
            timeoutSeconds: {{ $timeout }}
            failureThreshold: {{ $fail }}

      volumes:
        - name: oradata
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{ else }}{{ include "oracle-db.fullname" . }}{{ end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if and .Values.initSql.enabled .Values.initSql.files }}
        - name: init-sql
          configMap:
            name: {{ include "oracle-db.fullname" . }}-init-sql
        {{- end }}
