{{- if not .Values.existingSecretName }}
{{- $name := printf "%s-credentials" (include "oracle-db.fullname" .) -}}
{{- $ns := .Release.Namespace -}}
{{- $existing := (lookup "v1" "Secret" $ns $name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "oracle-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  ORACLE_PASSWORD: "{{- if .Values.oraclePassword -}}{{ .Values.oraclePassword }}{{- else if $existing -}}{{ index $existing.data "ORACLE_PASSWORD" | b64dec }}{{- else -}}{{ randAlphaNum 20 }}{{- end }}"
{{- end }}
