{{- if not .Values.existingSecretName }}
{{- $name := printf "%s-credentials" (include "oracle-db.fullname" .) -}}
{{- $ns := .Release.Namespace -}}
{{- $existing := (lookup "v1" "Secret" $ns $name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "oracle-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_USER_PASSWORD: {{- if .Values.oraclePassword -}}
    {{ .Values.oraclePassword | quote }}
  {{- else if $existing -}}
    {{ index $existing.data "APP_USER_PASSWORD" | b64dec | quote }}
  {{- else -}}
    {{ randAlphaNum 20 | quote }}
  {{- end }}
{{- end }}
