{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracle-db.fullname" . }}-credentials
  labels:
    {{- include "oracle-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  ORACLE_PASSWORD: {{ required "Provide .Values.oraclePassword or use existingSecretName" .Values.oraclePassword | quote }}
{{- end }}
