{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracle-db.fullname" . }}-credentials
  labels:
    {{- include "oracle-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  ORACLE_PASSWORD: {{ required "oraclePassword is empty and existingSecretName not set. Either set .Values.oraclePassword or pass an existingSecretName." .Values.oraclePassword | quote }}
{{- end }}
