tempo:
  image:
    repository: grafana/tempo
    tag: 2.3.1

  service:
    type: ClusterIP
    port: 3200

  config: |
    multitenancy_enabled: false

    server:
      http_listen_port: 3200

    distributor:
      receivers:
        jaeger:
          protocols:
            grpc:
            thrift_binary:
            thrift_compact:
            thrift_http:
        otlp:
          protocols:
            grpc:
            http:
        zipkin:

    ingester:
      trace_idle_period: 10s
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 1h

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo
