tempo:
  image:
    repository: grafana/tempo
    tag: 2.3.1
    pullPolicy: IfNotPresent
  query:
    enabled: true
    traceql:
      enabled: true

  service:
    type: NodePort
    ports:
      - name: tempo-ui
        port: 3200
        targetPort: 3200
        nodePort: 32532
      - name: otlp-http
        port: 4318
        targetPort: 4318
        nodePort: 32418   # You can choose another free NodePort (30000-32767)

  config: |
    multitenancy_enabled: false

    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:
        zipkin:
        jaeger:
          protocols:
            grpc:
            thrift_binary:
            thrift_compact:
            thrift_http:

    ingester:
      trace_idle_period: 10s
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 1h

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo
