apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: my-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
      app.kubernetes.io/instance: my-jenkins
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins
        app.kubernetes.io/instance: my-jenkins
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home

      containers:
        - name: jenkins
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              hostPort: 7070   # bind node port 7070
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home

      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName | default "my-jenkins-pvc" }}
