apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: my-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
      app.kubernetes.io/instance: my-jenkins
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins
        app.kubernetes.io/instance: my-jenkins
    spec:
      securityContext:
        fsGroup: 1000

      # ✅ Define the volume that matches volumeMounts.name = jenkins-home
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-pvc" (include "jenkins.fullname" .)) (.Values.persistence.existingClaim | default .Values.persistence.claimName) }}
        {{- else }}
        - name: jenkins-home
          emptyDir: {}
        {{- end }}

      initContainers:
        - name: volume-permissions
          image: busybox:1.36.1
          command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home

      containers:
        - name: jenkins
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8080
              # ❗ Prefer NodePort on the Service; hostPort is usually unnecessary and can block scheduling
              # hostPort: {{ .Values.service.nodePort | default 7070 }}
            - name: agent
              containerPort: 50000
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 120 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 30 }}
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 180 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 20 }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
            runAsGroup: {{ .Values.securityContext.runAsGroup | default 1000 }}
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
