{{- /* templates/pvc.yaml */ -}}
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-pvc" (include "jenkins.fullname" .)) .Values.persistence.claimName }}
  labels:
    app.kubernetes.io/name: {{ include "jenkins.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    {{- if .Values.persistence.accessModes }}
    {{- toYaml .Values.persistence.accessModes | nindent 2 }}
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "50Gi" }}
  {{- if and (hasKey .Values.persistence "storageClass") .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
