apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmak-data
  labels:
    app: cmak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust size as needed
