apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  type: {{ .Values.tempo.service.type }}
  selector:
    app: tempo
  ports:
    - protocol: TCP
      port: {{ .Values.tempo.service.port }}
      targetPort: 3200