apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  type: {{ .Values.tempo.service.type }}
  selector:
    app: tempo
  ports:
  {{- range .Values.tempo.service.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      nodePort: {{ .nodePort }}
  {{- end }}
