image:
  repository: prom/prometheus
  tag: v2.54.1
  pullPolicy: IfNotPresent

replicaCount: 1

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 9090
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: prometheus.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # - secretName: prometheus-tls
  #   hosts:
  #   - prometheus.local

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: 8Gi
  storageClass: ""  # set to your StorageClass or leave empty to use default

extraScrapeConfigs: []
  # - job_name: 'example'
  #   static_configs:
  #     - targets: ['my-app:8080']

retention: 15d
evaluationInterval: 30s
scrapeInterval: 15s
