apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}-config
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  loki-config.yaml: |
    {{- toYaml .Values.lokiConfig | nindent 4 }}
