apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
        - name: init-loki-dirs
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /var/loki/wal /var/loki/index /var/loki/boltdb-cache /var/loki/chunks
              chown -R 10001:10001 /var/loki
          volumeMounts:
            - name: loki-storage
              mountPath: /var/loki

      containers:
        - name: loki
          image: grafana/loki:2.9.0
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/config.yaml"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
              readOnly: true
            - name: loki-storage
              mountPath: /var/loki

      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-storage
