{{- if and .Values.operator.enabled .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" .Release.Name "operator" }}
  labels:
    app.kubernetes.io/name: kube-prometheus-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  {{- with .Values.commonAnnotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    resourceNames:
      - alertmanagers.monitoring.coreos.com
      - podmonitors.monitoring.coreos.com
      - prometheuses.monitoring.coreos.com
      - prometheusrules.monitoring.coreos.com
      - servicemonitors.monitoring.coreos.com
      - thanosrulers.monitoring.coreos.com
      - probes.monitoring.coreos.com
      - scrapeconfigs.monitoring.coreos.com
      - prometheusagents.monitoring.coreos.com
    verbs: ["get","update","patch"]
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - alertmanagers
      - alertmanagers/status
      - alertmanagers/finalizers
      - alertmanagerconfigs
      - prometheuses
      - prometheuses/status
      - prometheuses/finalizers
      - thanosrulers
      - thanosrulers/finalizers
      - thanosrulers/status
      - servicemonitors
      - podmonitors
      - probes
      - prometheusrules
      - scrapeconfigs
      - prometheusagents
      - prometheusagents/finalizers
      - prometheusagents/status
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps","secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list","delete"]
  - apiGroups: [""]
    resources: ["services","services/finalizers","endpoints"]
    verbs: ["get","create","update","delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["patch","create"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","list","watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get"]
{{- end }}
