apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Release.Name }}   # or include "wso2am.fullname"
data:
  deployment.toml: |-
{{- required "values.deploymentToml is required" .Values.deploymentToml | nindent 4 }}
