apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2apim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wso2apim
  template:
    metadata:
      labels:
        app: wso2apim
    spec:
      containers:
        - name: wso2apim
          image: wso2/wso2am:4.4.0
          ports:
            - containerPort: 9443
            - containerPort: 8280
            - containerPort: 8243
          volumeMounts:
            - name: config-volume
              mountPath: /home/wso2carbon/wso2am-4.4.0/repository/conf/deployment.toml
              subPath: deployment.toml
      volumes:
        - name: config-volume
          configMap:
            name: wso2apim-config
