apiVersion: v1
kind: Service
metadata:
  name: wso2apim
spec:
  type: NodePort
  selector:
    app: wso2apim
  ports:
    - port: 9443
      targetPort: 9443
      nodePort: 30443
    - port: 8280
      targetPort: 8280
      nodePort: 30280
    - port: 8243
      targetPort: 8243
      nodePort: 30243
