apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrape-config
  namespace: monitoring
stringData:
  additional-scrape-config.yaml: |
    # --- INTERNAL MICROSERVICES ---
    - job_name: "configserver"
      metrics_path: "/actuator/prometheus"
      static_configs:
        - targets: ["configserver:8071"]

    - job_name: "eurekaserver"
      metrics_path: "/actuator/prometheus"
      static_configs:
        - targets: ["eurekaserver:9001"]

    - job_name: "account"
      metrics_path: "/actuator/prometheus"
      static_configs:
        - targets: ["account:8080"]

    - job_name: "loan"
      metrics_path: "/actuator/prometheus"
      static_configs:
        - targets: ["loan:8090"]

    - job_name: "card"
      metrics_path: "/actuator/prometheus"
      static_configs:
        - targets: ["card:8070"]

    - job_name: "gatewayserver"
      metrics_path: "/actuator/prometheus"
      static_configs:
        - targets: ["gatewayserver:8072"]

    # --- PUBLIC INTERNET TARGETS ---
    - job_name: "prometheus-demo"
      metrics_path: /
      static_configs:
        - targets: ["prometheus.demo.do.prometheus.io:9090"]

    - job_name: "grafana-labs-mimir"
      metrics_path: /metrics
      static_configs:
        - targets: ["mimir-prod-1.grafana.net:443"]
      scheme: https

    - job_name: "grafana-labs-loki"
      metrics_path: /metrics
      static_configs:
        - targets: ["loki-prod-1.grafana.net:443"]
      scheme: https

    - job_name: "etcd-monitoring"
      static_configs:
        - targets: ["metrics.etcd.io:443"]
      scheme: https
