{{- if and (or (eq .Values.storage.mode "badger") .Values.storage.badger.enabled) .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jaeger.fullname" . }}-badger
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  accessModes: {{- toYaml .Values.persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jaeger.fullname" . }}-badger-index
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  accessModes: {{- toYaml .Values.persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
